nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./code:/code
        - ./container/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7.1-fpm
    volumes:
        - ./code:/code
